import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers":
    "authorization, x-client-info, apikey, content-type, x-supabase-client-platform, x-supabase-client-platform-version, x-supabase-client-runtime, x-supabase-client-runtime-version",
};

function jsonResponse(body: Record<string, unknown>, status = 200) {
  return new Response(JSON.stringify(body), {
    status,
    headers: { ...corsHeaders, "Content-Type": "application/json" },
  });
}

/** HMAC token used to prove the webhook URL was generated by create-checkout */
async function signCheckoutId(checkoutId: string, secret: string): Promise<string> {
  const key = await crypto.subtle.importKey(
    "raw",
    new TextEncoder().encode(secret),
    { name: "HMAC", hash: "SHA-256" },
    false,
    ["sign"],
  );
  const sig = await crypto.subtle.sign("HMAC", key, new TextEncoder().encode(checkoutId));
  return Array.from(new Uint8Array(sig))
    .map((b) => b.toString(16).padStart(2, "0"))
    .join("")
    .slice(0, 32);
}

function timingSafeEqual(a: string, b: string): boolean {
  if (a.length !== b.length) return false;
  let diff = 0;
  for (let i = 0; i < a.length; i++) diff |= a.charCodeAt(i) ^ b.charCodeAt(i);
  return diff === 0;
}

Deno.serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response(null, { headers: corsHeaders });
  }

  if (req.method !== "POST") {
    return jsonResponse({ received: true, action: "ignored" });
  }

  const supabaseUrl = Deno.env.get("SUPABASE_URL")!;
  const serviceRoleKey = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
  const supabase = createClient(supabaseUrl, serviceRoleKey);

  try {
    // ── Parse body ──
    let body: Record<string, unknown> = {};
    const contentType = req.headers.get("content-type") || "";

    if (contentType.includes("application/json")) {
      body = await req.json();
    } else if (contentType.includes("application/x-www-form-urlencoded")) {
      const text = await req.text();
      const params = new URLSearchParams(text);
      for (const [key, value] of params) body[key] = value;
    } else {
      try { body = await req.json(); } catch { body = {}; }
    }

    console.log(`[Webhook] Raw body:`, JSON.stringify(body).slice(0, 800));

    const url = new URL(req.url);
    const providerParam = url.searchParams.get("provider") || "";

    let checkoutId: string | null = null;
    let paymentStatus: "paid" | "failed" | "pending" = "pending";

    // ─── Detect InfinityPay by payload content (transaction_nsu field) ───
    const isInfinityPay = providerParam === "infinitypay" || body.transaction_nsu !== undefined;

    if (isInfinityPay) {
      checkoutId = (body.order_nsu || body.transaction_nsu) as string || null;

      const paidAmount = Number(body.paid_amount ?? body.amount ?? 0);
      const hasReceiptUrl = !!(body.receipt_url);

      // ── 1) Autenticidade: token HMAC gerado pelo create-checkout ──
      const token = url.searchParams.get("t") || "";
      if (!checkoutId) {
        console.warn("[InfinityPay] Sem order_nsu. Ignorando.");
        return jsonResponse({ received: true, action: "ignored" });
      }
      const expectedToken = await signCheckoutId(checkoutId, serviceRoleKey);
      if (!timingSafeEqual(token, expectedToken)) {
        console.error("[InfinityPay] Token de webhook inválido. Requisição rejeitada.");
        return jsonResponse({ error: "invalid_signature" }, 401);
      }

      // ── 2) Integridade do valor: precisa bater com o total do checkout ──
      const { data: pcRow } = await supabase
        .from("pending_checkouts")
        .select("total")
        .eq("id", checkoutId)
        .maybeSingle();

      if (!pcRow) {
        console.warn("[InfinityPay] Checkout inexistente:", checkoutId);
        return jsonResponse({ received: true, action: "ignored" });
      }

      const expectedCents = Math.round(Number(pcRow.total) * 100);
      // InfinityPay envia centavos; aceitamos reais por segurança de formato
      const paidCents = paidAmount >= expectedCents - 1
        ? Math.round(paidAmount)
        : Math.round(paidAmount * 100);
      const amountOk = Math.abs(paidCents - expectedCents) <= 1;

      console.log(`[InfinityPay] order_nsu=${body.order_nsu}, transaction_nsu=${body.transaction_nsu}`);
      console.log(`[InfinityPay] paid_amount=${body.paid_amount}, receipt_url=${body.receipt_url}`);

      if (paidAmount > 0 && hasReceiptUrl && amountOk) {
        paymentStatus = "paid";
      } else if (
        body.status === "failed" || body.status === "rejected" || body.status === "cancelled"
      ) {
        paymentStatus = "failed";
      } else if (paidAmount > 0 && !amountOk) {
        console.error(
          `[InfinityPay] Valor divergente: pago=${paidCents} esperado=${expectedCents}. Não confirmando.`,
        );
        return jsonResponse({ received: true, action: "amount_mismatch" });
      }

      console.log(`[InfinityPay] Status detectado: ${paymentStatus}`);
    }
    // ─── Mercado Pago ───
    else if (providerParam === "mercadopago") {
      const action = body.action as string || body.type as string || "";
      const data = (body.data || {}) as Record<string, unknown>;

      if (action.startsWith("payment") && data.id) {
        const mpPaymentId = String(data.id);

        const { data: checkout } = await supabase
          .from("pending_checkouts")
          .select("id, store_id")
          .eq("provider", "mercadopago")
          .eq("status", "pending")
          .limit(10);

        if (checkout && checkout.length > 0) {
          const storeId = checkout[0].store_id;
          const { data: secretsRow } = await supabase
            .from("store_checkout_secrets")
            .select("checkout_config")
            .eq("store_id", storeId)
            .single();

          const accessToken = (secretsRow?.checkout_config as Record<string, string>)?.access_token;
          if (accessToken) {
            const mpResp = await fetch(`https://api.mercadopago.com/v1/payments/${mpPaymentId}`, {
              headers: { Authorization: `Bearer ${accessToken}` },
            });
            if (mpResp.ok) {
              const mpData = await mpResp.json();
              checkoutId = mpData.external_reference;
              if (mpData.status === "approved") paymentStatus = "paid";
              else if (["rejected", "cancelled", "refunded"].includes(mpData.status)) paymentStatus = "failed";
            }
          }
        }
      }
    } else {
      console.log("[Webhook] Payload não reconhecido. Ignorando.");
      return jsonResponse({ received: true, action: "ignored" });
    }

    // Fallback checkout ID
    if (!checkoutId) {
      checkoutId = (body.checkout_id || body.external_reference || body.order_nsu || body.reference) as string || null;
    }

    if (!checkoutId) {
      console.log("[Webhook] Nenhum checkout_id encontrado. Ignorando.");
      return jsonResponse({ received: true, action: "ignored" });
    }

    console.log(`[Webhook] checkout_id=${checkoutId}, paymentStatus=${paymentStatus}`);

    if (paymentStatus === "pending") {
      return jsonResponse({ received: true, action: "no_change" });
    }

    if (paymentStatus === "paid") {
      // ── ATOMIC CLAIM: prevents race condition with expire cron ──
      // Uses FOR UPDATE SKIP LOCKED — if expire cron already locked/expired this row,
      // claim returns NULL and we safely skip (no double stock restoration).
      const providerRef = String(body.transaction_nsu || body.order_nsu || checkoutId);
      const { data: claimedCheckout, error: claimError } = await supabase
        .rpc("claim_checkout_for_payment", {
          p_checkout_id: checkoutId,
          p_provider_reference: providerRef,
        });

      if (claimError) {
        console.error("[Webhook] Erro ao clamar checkout:", claimError);
        return jsonResponse({ received: true, error: "claim_failed" });
      }

      if (!claimedCheckout) {
        console.log("[Webhook] Checkout já processado (expirado ou pago). Ignorando.");
        return jsonResponse({ received: true, action: "already_processed" });
      }

      const pc = claimedCheckout as Record<string, unknown>;
      const pcItems = pc.items as Array<Record<string, unknown>>;
      const pcOrderType = (pc.order_type as string) || "instant";
      const pcHasMixedCart = !!pc.has_mixed_cart;
      const pcDeliveryFeeMode = (pc.delivery_fee_mode as string) || "instant_only";

      const baseOrderData = {
        store_id: pc.store_id as string,
        customer_name: pc.customer_name as string,
        customer_phone: pc.customer_phone as string,
        customer_address: pc.customer_address as string,
        customer_maps_url: (pc.customer_maps_url as string) || null,
        delivery_type: pc.delivery_type as string,
        payment_method: "online",
        notes: pc.notes as string,
        status: "confirmed",
      };

      const createdOrders: string[] = [];

      if (pcHasMixedCart) {
        // ── Split: Instant + Preorder (best-effort: both attempts run independently) ──
        const instantItems = pcItems.filter((i: any) => (i.fulfillment_choice || "instant") === "instant");
        const preorderItems = pcItems.filter((i: any) => i.fulfillment_choice === "preorder");

        if (instantItems.length > 0) {
          const instantSubtotal = instantItems.reduce((s: number, i: any) => s + Number(i.total_price || 0), 0);
          const instantDeliveryFee = pcDeliveryFeeMode === "instant_only" ? Number(pc.delivery_fee || 0) : 0;
          try {
            const { data: o1, error: e1 } = await supabase.from("orders").insert({
              ...baseOrderData,
              items: instantItems,
              subtotal: instantSubtotal,
              delivery_fee: instantDeliveryFee,
              total: instantSubtotal + instantDeliveryFee,
              order_type: "instant",
            }).select().single();
            if (e1) console.error("[Webhook] Erro pedido instant:", e1);
            else {
              createdOrders.push(o1.id);
              await supabase.rpc("decrement_ingredients_on_sale", { p_items: instantItems, p_store_id: pc.store_id });
            }
          } catch (err) {
            console.error("[Webhook] CRITICAL: instant order insert threw:", err);
          }
        }

        if (preorderItems.length > 0) {
          const preorderSubtotal = preorderItems.reduce((s: number, i: any) => s + Number(i.total_price || 0), 0);
          const preorderDeliveryFee = pcDeliveryFeeMode === "instant_only" ? 0 : Number(pc.delivery_fee || 0);
          const preorderTotal = preorderSubtotal + preorderDeliveryFee;
          try {
            const { data: o2, error: e2 } = await supabase.from("orders").insert({
              ...baseOrderData,
              items: preorderItems,
              subtotal: preorderSubtotal,
              delivery_fee: preorderDeliveryFee,
              total: preorderTotal,
              order_type: "preorder",
              scheduled_date: pc.scheduled_date || null,
              scheduled_time: pc.scheduled_time || null,
              deposit_amount: pc.deposit_amount ? Number(pc.deposit_amount) : null,
              deposit_status: pc.deposit_amount ? "paid" : null,
            }).select().single();
            if (e2) console.error("[Webhook] Erro pedido preorder:", e2);
            else {
              createdOrders.push(o2.id);
              await supabase.rpc("decrement_ingredients_on_sale", { p_items: preorderItems, p_store_id: pc.store_id });
            }
          } catch (err) {
            console.error("[Webhook] CRITICAL: preorder order insert threw:", err);
          }
        }

        if (createdOrders.length === 0) {
          console.error("[Webhook] CRITICAL: Nenhum pedido criado no split. checkout_id=", checkoutId);
          return jsonResponse({ received: true, error: "both_inserts_failed" });
        }
      } else {
        // ── Single order ──
        const { data: order, error: orderError } = await supabase
          .from("orders")
          .insert({
            ...baseOrderData,
            items: pc.items,
            subtotal: pc.subtotal as number,
            delivery_fee: pc.delivery_fee as number,
            total: pc.total as number,
            order_type: pcOrderType,
            scheduled_date: pc.scheduled_date || null,
            scheduled_time: pc.scheduled_time || null,
            deposit_amount: pc.deposit_amount ? Number(pc.deposit_amount) : null,
            deposit_status: pc.deposit_amount ? "paid" : null,
          })
          .select()
          .single();

        if (orderError) {
          console.error("[Webhook] Erro ao criar pedido:", orderError);
          return jsonResponse({ received: true, error: "Failed to create order" });
        }
        createdOrders.push(order.id);
        await supabase.rpc("decrement_ingredients_on_sale", { p_items: pc.items, p_store_id: pc.store_id as string });
      }

      // ── Push notification ao lojista ──
      for (const oid of createdOrders) {
        try {
          const pushResp = await fetch(`${supabaseUrl}/functions/v1/push-notify`, {
            method: "POST",
            headers: {
              "Content-Type": "application/json",
              "Authorization": `Bearer ${serviceRoleKey}`,
            },
            body: JSON.stringify({ record: { id: oid, store_id: pc.store_id } }),
          });
          console.log("[Webhook] Push notify status:", pushResp.status);
        } catch (pushErr) {
          console.error("[Webhook] Push notify error (non-fatal):", pushErr);
        }
      }

      console.log("[Webhook] ✅ Pedidos criados:", createdOrders.join(", "));
      return jsonResponse({ received: true, action: "order_created", order_ids: createdOrders });
    }

    if (paymentStatus === "failed") {
      // Atualizar para "failed" — o trigger handle_checkout_status_change
      // detecta failed e chama release_checkout_stock automaticamente
      await supabase
        .from("pending_checkouts")
        .update({ status: "failed" })
        .eq("id", checkoutId);

      console.log("[Webhook] ❌ Pagamento falhou. Estoque restaurado automaticamente pelo trigger.");
      return jsonResponse({ received: true, action: "marked_failed" });
    }

    // Status still pending — no action
    const { data: pendingCheckout } = await supabase
      .from("pending_checkouts")
      .select("status")
      .eq("id", checkoutId)
      .single();

    if (!pendingCheckout || pendingCheckout.status !== "pending") {
      return jsonResponse({ received: true, action: "already_processed" });
    }

    return jsonResponse({ received: true });
  } catch (err) {
    console.error("[Webhook] Erro:", err);
    return jsonResponse({ received: true, error: (err as Error).message });
  }
});
